import { ROLES } from './roles';
import { ROUTES } from './routes';

export const PERMISSIONS = {
  [ROLES.ADMIN]: [ROUTES.ADMIN_DASHBOARD, ROUTES.DASHBOARD, ROUTES.HOME],
  [ROLES.GUEST]: [ROUTES.HOME, ROUTES.LOGIN, ROUTES.REGISTER],
  [ROLES.STUDENT]: [ROUTES.STUDENT_DASHBOARD, ROUTES.DASHBOARD, ROUTES.HOME],
  [ROLES.TEACHER]: [ROUTES.HOME, ROUTES.DASHBOARD],
};
