export const ROLES = {
  ADMIN: 'PLATFORM_ADMIN',
  LICENSE_USER: 'LICENSE_USER',
  PRIVATE_USER: 'PRIVATE_USER',
  COMPANY_EMPLOYEE: 'COMPANY_EMPLOYEE',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
};
